Feat: Add account snippet of Dart
2002Bishwajeet/awesome-appwrite-snippets pull request #19
Opened 2022-10-08 05:10 UTC by Rajat379

## Description  
Adds support for Account API snippets in language Dart.

## Testing  
- [x] Manual QA 

## Checklist  
- [x] Followed the [contribution guidelines](https://github.com/2002Bishwajeet/awesome-appwrite-snippets/blob/master/CONTRIBUTING.md)  
- [x] The code is commented properly to give appropriate context.

2022-10-08 08:31 UTC, 2002Bishwajeet requested changes
Hey, Thanks for the PR, looks like you made snippets for the client SDK and not the server SDK. I would request you to double-check again and re request review from me.

You need to take reference from this https://appwrite.io/docs/server/account?sdk=dart-default

2022-10-08 08:31 UTC, 2002Bishwajeet commented on snippets/dart/account.code-snippets
> +      "prefix": ["account"],
Prefix all the server snippets with `s` please. This would prevent for conflicting between the client and server SDKs

2022-10-08 08:31 UTC, 2002Bishwajeet commented on snippets/dart/account.code-snippets
> +      "body": ["final Account ${1:account} = Account(client);"],
```suggestion
      "body": ["final Account ${1:account} = Account(${2:client});"],
```

2022-10-08 08:31 UTC, 2002Bishwajeet commented on snippets/dart/account.code-snippets
> +    "Create account": {
I don't think this API exists for the server side. Please remove this

2022-10-08 08:31 UTC, 2002Bishwajeet commented on snippets/dart/account.code-snippets
> +    "Create account Session with Email": {
Same goes here

2022-10-08 08:31 UTC, 2002Bishwajeet commented on snippets/dart/account.code-snippets
> +    "Create account Session with OAuth2": {
And this

2022-10-08 08:31 UTC, 2002Bishwajeet commented on snippets/dart/account.code-snippets
> +    "Create Magic Url session": {
This

2022-10-08 09:04 UTC, Rajat379 commented
Hey, I made changes in this PR. Kindly re-review it.

2022-10-08 09:40 UTC, 2002Bishwajeet approved these changes
LGTM!

2022-10-08 09:59 UTC, Rajat379 commented
Hey, can this PR be merged now, or some other checks are pending?

2022-10-08 10:08 UTC, 2002Bishwajeet commented
I merge the PRs in Batches 🙂. Currently, there is one more PR that is still in progress and then after that, your PR will be merged.

If you are worrying about hacktoberfest, adding the `hacktoberfest-accepted` is there for to be counted for the hacktoberfest

2022-10-17 18:03 UTC, merged

2022-10-17 18:04 UTC, 2002Bishwajeet commented
Thank you for your Contribution✨

@all-contributors please add @Rajat379  for code